frame_id: "world"
child_frame_id: "stretch_head"
transform: 
  translation: 
    x: -0.845
    y: -1.070
    z: 1.434
  rotation: 
    x: 0.001
    y: 0.000
    z: -0.001
    w: 1.000
# Translation: [-0.845, -1.070, 1.434]
# - Rotation: in Quaternion [0.001, 0.000, -0.001, 1.000]
