# All the locations are in the world frame
frame: "world"

zones:
  zone_left:
    location: [0.0, 1.0, 0.0]
    orientation_z: 0.0
  zone_bottom:
    location: [-1.3, 0.0, 0.0]
    orientation_z: 1.57
  zone_right:
    location: [0.0, -0.8, 0.0]
    orientation_z: 3.14
  zone_top:
    location: [1.3, 0, 0.0]
    orientation_z: 4.71


objects:
  object_1:
    x_offset: 0.5
    color: "red"
    arm_length: 0.3
    zone: "zone_left"
  object_2:
    x_offset: -0.4
    orientation_z: 3.14
    color: "blue"
    arm_length: 0.2
    zone: "zone_left"
  object_3:
    x_offset: 0.1
    color: "green"
    arm_length: 0.3
    zone: "zone_top"
  object_4:
    x_offset: 0.3
    color: "yellow"
    arm_length: 0.3
    zone: "zone_right"
  object_5:
    x_offset: -0.5
    color: "red"
    arm_length: 0.2
    zone: "zone_right"
  object_6:
    x_offset: 0.0
    color: "blue"
    arm_length: 0.2
    zone: "zone_bottom"


  # User Objects
  object_7:
    x_offset: 0.38
    color: "red"
    arm_length: 0.32
    zone: "zone_left"
  object_8:
    x_offset: -0.7
    orientation_z: 3.14
    color: "blue"
    arm_length: 0.2
    zone: "zone_left"
  object_9:
    x_offset: 0.1
    color: "green"
    arm_length: 0.35
    zone: "zone_left"
  object_10:
    x_offset: -0.2
    color: "yellow"
    arm_length: 0.24
    zone: "zone_left"
  object_11:
    x_offset: 0.45
    color: "red"
    arm_length: 0.35
    zone: "zone_right"
  object_12:
    x_offset: 0.0
    color: "blue"
    arm_length: 0.20
    zone: "zone_right"
  object_13:
    x_offset: -0.3
    color: "red"
    arm_length: 0.3
    zone: "zone_right"
  object_14:
    x_offset: 0.15
    color: "yellow"
    arm_length: 0.27
    zone: "zone_right"
  object_15:
    x_offset: 0.2
    color: "green"
    arm_length: 0.2
    zone: "zone_top"
  object_16:
    x_offset: -0.2
    color: "yellow"
    arm_length: 0.3
    zone: "zone_top"
  object_17:
    x_offset: 0.0
    color: "green"
    arm_length: 0.35
    zone: "zone_top"
  object_18:
    x_offset: -0.28
    color: "yellow"
    arm_length: 0.18
    zone: "zone_bottom"
  object_19:
    x_offset: 0.1
    color: "green"
    arm_length: 0.29
    zone: "zone_bottom"
  object_20:
    x_offset: 0.3
    color: "blue"
    arm_length: 0.18
    zone: "zone_bottom"




dropoffs:
  red:
    location: [2.0, 1.0, 0.0]
    orientation_z: 1.57

  blue:
    location: [2.0, -1.25, 0]
    orientation_z: 1.57

  green:
    location: [-2, -1.25, 0]
    orientation_z: 4.71 

  yellow:
    location: [-2, 1.0, 0]
    orientation_z: 4.71 