objects:
  object_1:
    location: [0.5, 2.0, 0.0]
    orientation_z: 0.0
    color: "red"
    arm_length: 0.3
  object_2:
    location: [2.0, 1.0, 0.0]
    orientation_z: 4.71
    color: "blue"
    arm_length: 0.3
  object_3:
    location: [1.0, 0.0, 0.0]
    orientation_z: 3.14
    color: "blue"
    arm_length: 0.3


dropoffs:
  red:
    location: [2.5, 2.0, 0.0]
    orientation_z: 1.57

  blue:
    location: [2.5, -0.25, 0]
    orientation_z: 1.57

  green:
    location: [-1, -0.25, 0]
    orientation_z: 4.71 

  yellow:
    location: [-1, 2.0, 0]
    orientation_z: 4.71 