controller_list:
  - name: fake_Arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_lift
      - joint_arm_l3
      - joint_arm_l2
      - joint_arm_l1
      - joint_arm_l0
      - joint_wrist_yaw
      - joint_wrist_pitch
      - joint_wrist_roll
initial:  # Define initial robot poses per group
#  - group: Arm
#    pose: home

  []